// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.0
// source: service_finance_flow.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FinanceFlowServiceClient is the client API for FinanceFlowService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FinanceFlowServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
}

type financeFlowServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFinanceFlowServiceClient(cc grpc.ClientConnInterface) FinanceFlowServiceClient {
	return &financeFlowServiceClient{cc}
}

func (c *financeFlowServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/pb.FinanceFlowService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FinanceFlowServiceServer is the server API for FinanceFlowService service.
// All implementations must embed UnimplementedFinanceFlowServiceServer
// for forward compatibility
type FinanceFlowServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	mustEmbedUnimplementedFinanceFlowServiceServer()
}

// UnimplementedFinanceFlowServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFinanceFlowServiceServer struct {
}

func (UnimplementedFinanceFlowServiceServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedFinanceFlowServiceServer) mustEmbedUnimplementedFinanceFlowServiceServer() {}

// UnsafeFinanceFlowServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FinanceFlowServiceServer will
// result in compilation errors.
type UnsafeFinanceFlowServiceServer interface {
	mustEmbedUnimplementedFinanceFlowServiceServer()
}

func RegisterFinanceFlowServiceServer(s grpc.ServiceRegistrar, srv FinanceFlowServiceServer) {
	s.RegisterService(&FinanceFlowService_ServiceDesc, srv)
}

func _FinanceFlowService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceFlowServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FinanceFlowService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceFlowServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FinanceFlowService_ServiceDesc is the grpc.ServiceDesc for FinanceFlowService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FinanceFlowService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.FinanceFlowService",
	HandlerType: (*FinanceFlowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _FinanceFlowService_CreateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_finance_flow.proto",
}
