// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.0
// source: service_finance_flow.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FinanceFlowClient is the client API for FinanceFlow service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FinanceFlowClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
}

type financeFlowClient struct {
	cc grpc.ClientConnInterface
}

func NewFinanceFlowClient(cc grpc.ClientConnInterface) FinanceFlowClient {
	return &financeFlowClient{cc}
}

func (c *financeFlowClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/pb.FinanceFlow/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FinanceFlowServer is the server API for FinanceFlow service.
// All implementations must embed UnimplementedFinanceFlowServer
// for forward compatibility
type FinanceFlowServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	mustEmbedUnimplementedFinanceFlowServer()
}

// UnimplementedFinanceFlowServer must be embedded to have forward compatible implementations.
type UnimplementedFinanceFlowServer struct {
}

func (UnimplementedFinanceFlowServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedFinanceFlowServer) mustEmbedUnimplementedFinanceFlowServer() {}

// UnsafeFinanceFlowServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FinanceFlowServer will
// result in compilation errors.
type UnsafeFinanceFlowServer interface {
	mustEmbedUnimplementedFinanceFlowServer()
}

func RegisterFinanceFlowServer(s grpc.ServiceRegistrar, srv FinanceFlowServer) {
	s.RegisterService(&FinanceFlow_ServiceDesc, srv)
}

func _FinanceFlow_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceFlowServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FinanceFlow/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceFlowServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FinanceFlow_ServiceDesc is the grpc.ServiceDesc for FinanceFlow service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FinanceFlow_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.FinanceFlow",
	HandlerType: (*FinanceFlowServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _FinanceFlow_CreateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_finance_flow.proto",
}
