// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: account_transactions.sql

package db

import (
	"context"
)

const createAccountTransactions = `-- name: CreateAccountTransactions :one
INSERT INTO account_transactions (
  account_id,
  amount
) VALUES (
  $1, $2
) RETURNING id, account_id, amount, created_at
`

type CreateAccountTransactionsParams struct {
	AccountID int64 `json:"account_id"`
	Amount    int64 `json:"amount"`
}

func (q *Queries) CreateAccountTransactions(ctx context.Context, arg CreateAccountTransactionsParams) (AccountTransaction, error) {
	row := q.db.QueryRow(ctx, createAccountTransactions, arg.AccountID, arg.Amount)
	var i AccountTransaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountTransactions = `-- name: GetAccountTransactions :one
SELECT id, account_id, amount, created_at FROM account_transactions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAccountTransactions(ctx context.Context, id int64) (AccountTransaction, error) {
	row := q.db.QueryRow(ctx, getAccountTransactions, id)
	var i AccountTransaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const listAccountTransactions = `-- name: ListAccountTransactions :many
SELECT id, account_id, amount, created_at FROM account_transactions
WHERE account_id = $1
ORDER BY id
LIMIT $2
OFFSET $3
`

type ListAccountTransactionsParams struct {
	AccountID int64 `json:"account_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListAccountTransactions(ctx context.Context, arg ListAccountTransactionsParams) ([]AccountTransaction, error) {
	rows, err := q.db.Query(ctx, listAccountTransactions, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountTransaction{}
	for rows.Next() {
		var i AccountTransaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
